apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: todo-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kikodocker2004/todo-backend:v2  
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL       
          value: "postgresql://postgres:password123@db-service:5432/tododb"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: todo-namespace
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP